# Copyright (c) 2024-2025 Ziqi Fan
# SPDX-License-Identifier: Apache-2.0
# Flat Five-Bar Robot
# Modified by 515

wheel_leg/flat:
  model_name: "policy.pt"
  num_observations: 105
  observations: ["ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel"]
  observations_history: [4, 3, 2, 1, 0]  # 0 is the latest observation
  observations_history_priority: "time"  # "time" or "term" priority
  clip_obs: 100.0
  clip_actions_lower: [-1.0, -1.0, -1.0,
                       -1.0, -1.0, -1.0]
  clip_actions_upper: [1.0, 1.0, 1.0,
                       1.0, 1.0, 1.0]
  rl_kp: [25.0, 25.0,
          25.0, 25.0,
          0.0, 0.0]
  rl_kd: [1.0, 1.0,
          1.0, 1.0,
          2.0, 2.0]
  fixed_kp: [25.0, 25.0,
            25.0, 25.0,
            0.0, 0.0]
  fixed_kd: [1.0, 1.0,
            1.0, 1.0,
            2.0, 2.0]
  num_of_dofs: 6

  action_scale: [2.0, 2.0, 2.0,
                2.0, 50.0, 50.0]
  wheel_indices: [4, 5]
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.15
  commands_scale: [1.0, 1.0, 1.0]
  torque_limits: [30.0, 30.0,
                  30.0, 30.0,
                  3.0, 3.0]
  default_dof_pos: [ 0.0, 0.0,
                     0.0, 0.0,
                     0.0, 0.0]
  joint_mapping: [0, 1, 2, 3, 4, 5]
